"""Daily email digest generation and sending."""

import smtplib
import os
from datetime import datetime, timezone
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Any

from charon.db import get_applications


class DigestError(Exception):
    """Raised when digest generation or sending fails."""


STATUS_EMOJI = {
    "acknowledged": "\U0001f4e8",  # incoming envelope
    "responded": "\U0001f4ac",     # speech balloon
    "interviewing": "\U0001f3af",  # bullseye
    "offered": "\U0001f389",       # party popper
    "rejected": "\u274c",          # red X
    "ghosted": "\U0001f47b",       # ghost
    "applied": "\U0001f4e4",       # outbox tray
}

STATUS_COLOR = {
    "acknowledged": "#2196F3",  # blue
    "responded": "#FF9800",     # orange
    "interviewing": "#9C27B0",  # purple
    "offered": "#4CAF50",       # green
    "rejected": "#F44336",      # red
    "ghosted": "#9E9E9E",       # grey
    "applied": "#607D8B",       # blue-grey
}

# Display order for status grouping (most important first)
STATUS_ORDER = [
    "interviewing", "offered", "responded", "acknowledged",
    "applied", "ghosted", "rejected",
]


def _build_html_digest(apps: list[dict], today: str) -> str:
    """Build an HTML digest showing all application statuses."""
    # Group by status
    by_status: dict[str, list[dict]] = {}
    for app in apps:
        by_status.setdefault(app["status"], []).append(app)

    # Summary counts
    total = len(apps)
    counts = {s: len(by_status.get(s, [])) for s in STATUS_ORDER if s in by_status}
    summary_parts = []
    for s, c in counts.items():
        color = STATUS_COLOR.get(s, "#607D8B")
        summary_parts.append(f'<strong style="color:{color}">{c}</strong> {s}')
    summary_line = ", ".join(summary_parts)

    # Build table rows
    rows = ""
    for i, app in enumerate(apps):
        bg = "#f8f9fa" if i % 2 == 0 else "#ffffff"
        status = app["status"]
        emoji = STATUS_EMOJI.get(status, "\U0001f4e7")
        color = STATUS_COLOR.get(status, "#607D8B")
        applied = app.get("applied_at", "")[:10]
        rows += f'''<tr style="background-color:{bg}">
            <td style="padding:8px 12px;border-bottom:1px solid #e0e0e0;color:#212121">{app["company"]}</td>
            <td style="padding:8px 12px;border-bottom:1px solid #e0e0e0;color:#212121;font-size:13px">{app["role"]}</td>
            <td style="padding:8px 12px;border-bottom:1px solid #e0e0e0">
                <span style="color:{color};font-weight:bold">{emoji} {status.upper()}</span>
            </td>
            <td style="padding:8px 12px;border-bottom:1px solid #e0e0e0;color:#888;font-size:12px">{applied}</td>
        </tr>'''

    return f'''<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background-color:#1a1a2e;font-family:Consolas,'Courier New',monospace">
    <div style="max-width:700px;margin:20px auto;background-color:#16213e;border-radius:8px;overflow:hidden;border:1px solid #0f3460">
        <div style="background:linear-gradient(135deg,#0f3460,#1a1a2e);padding:24px;text-align:center;border-bottom:2px solid #e94560">
            <h1 style="color:#e94560;margin:0;font-size:28px;letter-spacing:3px">\u2620\ufe0f CHARON</h1>
            <p style="color:#a0a0b0;margin:6px 0 0;font-size:14px">Daily Digest &mdash; {today}</p>
        </div>
        <div style="padding:20px 24px;color:#d0d0d0;font-size:14px;line-height:1.6">
            <p style="color:#a0a0b0;margin:0 0 16px">
                Tracking <strong style="color:#e0e0e0">{total}</strong> applications &mdash; {summary_line}
            </p>
            <table style="width:100%;border-collapse:collapse;border-radius:6px;overflow:hidden;border:1px solid #e0e0e0">
                <tr style="background-color:#263238;color:#ffffff">
                    <th style="padding:10px 12px;text-align:left">Company</th>
                    <th style="padding:10px 12px;text-align:left">Role</th>
                    <th style="padding:10px 12px;text-align:left">Status</th>
                    <th style="padding:10px 12px;text-align:left">Applied</th>
                </tr>
                {rows}
            </table>
        </div>
        <div style="background-color:#0f3460;padding:16px;text-align:center;border-top:1px solid #1a1a2e">
            <p style="color:#606080;margin:0;font-size:12px">\u2693 Generated by Charon &mdash; Getting you to the other side.</p>
        </div>
    </div>
</body>
</html>'''


def _build_plaintext_digest(apps: list[dict], today: str) -> str:
    """Build a plain text digest showing all application statuses."""
    lines = [
        "=" * 60,
        "  CHARON - Daily Digest",
        f"  {today}",
        "=" * 60,
        "",
        f"  Tracking {len(apps)} application(s)",
        "",
    ]

    # Group by status for display
    by_status: dict[str, list[dict]] = {}
    for app in apps:
        by_status.setdefault(app["status"], []).append(app)

    status_markers = {
        "interviewing": "[>>>]", "offered": "[!!!]", "responded": "[<->]",
        "acknowledged": "[<-]", "applied": "[->]", "ghosted": "[X]", "rejected": "[X]",
    }

    for status in STATUS_ORDER:
        group = by_status.get(status, [])
        if not group:
            continue
        lines.append(f"=== {status.upper()} ({len(group)}) ===")
        lines.append("")
        marker = status_markers.get(status, "[ ]")
        for app in group:
            lines.append(f"  {marker} {app['company']}: {app['role']}")
        lines.append("")

    lines.append("-" * 60)
    lines.append("Generated by Charon - Getting you to the other side.")
    return "\n".join(lines)


def build_digest() -> tuple[str, str, str]:
    """Build the digest from current application statuses.

    Returns (subject, plaintext, html). Empty strings if no apps.
    """
    apps = get_applications()
    if not apps:
        return "", "", ""

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    subject = f"\u2620\ufe0f Charon Digest - {today}"

    # Sort by status priority, then by company name
    status_rank = {s: i for i, s in enumerate(STATUS_ORDER)}
    apps.sort(key=lambda a: (status_rank.get(a["status"], 99), a["company"].lower()))

    plaintext = _build_plaintext_digest(apps, today)
    html = _build_html_digest(apps, today)

    return subject, plaintext, html


def send_digest(profile: dict[str, Any]) -> bool:
    """Send the digest email. Returns True if sent successfully."""
    notif = profile.get("notifications", {})
    if not notif.get("enabled", False):
        raise DigestError(
            "Notifications disabled. Enable in profile:\n"
            "  notifications.enabled: true"
        )

    mail_server = notif.get("mail_server", "")
    mail_port = notif.get("mail_port", 587)
    mail_from = notif.get("mail_from", "")
    mail_to_raw = notif.get("mail_to", "")
    if isinstance(mail_to_raw, list):
        mail_to_list = [addr.strip() for addr in mail_to_raw if addr and addr.strip()]
    elif isinstance(mail_to_raw, str) and mail_to_raw:
        mail_to_list = [addr.strip() for addr in mail_to_raw.split(",") if addr.strip()]
    else:
        mail_to_list = []
    mail_to = ", ".join(mail_to_list)
    mail_user = notif.get("mail_user", "")
    mail_pass = notif.get("mail_pass", "") or os.environ.get("CHARON_MAIL_PASS", "")

    if not mail_server or not mail_from or not mail_to_list:
        raise DigestError(
            "Mail not configured. Set mail_server, mail_from, and mail_to in profile."
        )

    subject, plaintext, html = build_digest()

    if not plaintext:
        return False

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = mail_from
    msg["To"] = mail_to
    msg.attach(MIMEText(plaintext, "plain", "utf-8"))
    msg.attach(MIMEText(html, "html", "utf-8"))

    try:
        with smtplib.SMTP(mail_server, mail_port, timeout=30) as server:
            server.ehlo()
            if server.has_extn("STARTTLS"):
                server.starttls()
                server.ehlo()
            if mail_user and mail_pass:
                server.login(mail_user, mail_pass)
            server.sendmail(mail_from, mail_to_list, msg.as_string())
    except smtplib.SMTPAuthenticationError:
        raise DigestError("SMTP authentication failed. Check mail_user and CHARON_MAIL_PASS.")
    except smtplib.SMTPException as e:
        raise DigestError(f"SMTP error: {type(e).__name__}. Check mail settings.")
    except OSError as e:
        raise DigestError(f"Connection failed: {e}. Check mail_server and mail_port.")

    return True


def preview_digest() -> str:
    """Generate digest preview without sending. Returns the body text."""
    _, plaintext, _ = build_digest()
    return plaintext
