"""Daily email digest generation and sending."""

import json
import smtplib
import os
from datetime import datetime, timezone
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Any

from charon.db import get_unsent_digest, mark_digest_sent


class DigestError(Exception):
    """Raised when digest generation or sending fails."""


def build_digest() -> tuple[str, str, list[int]]:
    """Build the digest content. Returns (subject, body_text, entry_ids).

    Returns empty strings if nothing to report.
    """
    entries = get_unsent_digest()
    if not entries:
        return "", "", []

    entry_ids = [e["id"] for e in entries]
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    subject = f"Charon Digest - {today}"

    lines = [
        "=" * 60,
        "  CHARON - Daily Digest",
        f"  {today}",
        "=" * 60,
        "",
    ]

    # Group entries by type
    by_type: dict[str, list[dict]] = {}
    for entry in entries:
        etype = entry.get("entry_type", "other")
        by_type.setdefault(etype, []).append(entry)

    # Responses section (Phase 5 — will go at top when implemented)
    responses = by_type.pop("response", [])
    if responses:
        lines.append("=== RESPONSES RECEIVED ===")
        lines.append("")
        for r in responses:
            lines.append(f"  [!] {r['summary']}")
        lines.append("")

    # Ghosted section
    ghosted = by_type.pop("ghosted", [])
    if ghosted:
        lines.append("=== GHOSTED ===")
        lines.append("")
        for g in ghosted:
            lines.append(f"  [X] {g['summary']}")
        lines.append("")

    # Application updates
    applications = by_type.pop("application", [])
    if applications:
        lines.append("=== Applications ===")
        lines.append("")
        for a in applications:
            lines.append(f"  [>] {a['summary']}")
        lines.append("")

    # Activity section
    lines.append("=== Today's Activity ===")
    lines.append("")

    type_labels = {
        "ghostbust": "Ghost Job Analysis",
        "redflags": "Red Flag Scan",
        "dossier": "Company Dossier",
        "hunt": "Full Hunt",
        "watch": "Watchlist",
    }

    for etype, type_entries in by_type.items():
        label = type_labels.get(etype, etype.title())
        lines.append(f"--- {label} ---")
        for entry in type_entries:
            lines.append(f"  {entry['summary']}")
            # Include score details if available
            detail = entry.get("detail_json")
            if detail:
                try:
                    d = json.loads(detail) if isinstance(detail, str) else detail
                    if isinstance(d, dict):
                        score = d.get("ghost_score") or d.get("redflag_score") or d.get("weighted_score")
                        if score is not None:
                            lines.append(f"    Score: {score}")
                except (json.JSONDecodeError, TypeError):
                    pass
        lines.append("")

    lines.append("-" * 60)
    lines.append("Generated by Charon - Getting you to the other side.")

    body = "\n".join(lines)
    return subject, body, entry_ids


def send_digest(profile: dict[str, Any]) -> bool:
    """Send the digest email. Returns True if sent successfully."""
    notif = profile.get("notifications", {})
    if not notif.get("enabled", False):
        raise DigestError(
            "Notifications disabled. Enable in profile:\n"
            "  notifications.enabled: true"
        )

    mail_server = notif.get("mail_server", "")
    mail_port = notif.get("mail_port", 587)
    mail_from = notif.get("mail_from", "")
    mail_to_raw = notif.get("mail_to", "")
    # Support single string or list of addresses
    if isinstance(mail_to_raw, list):
        mail_to_list = [addr.strip() for addr in mail_to_raw if addr and addr.strip()]
    elif isinstance(mail_to_raw, str) and mail_to_raw:
        mail_to_list = [addr.strip() for addr in mail_to_raw.split(",") if addr.strip()]
    else:
        mail_to_list = []
    mail_to = ", ".join(mail_to_list)
    mail_user = notif.get("mail_user", "")
    mail_pass = notif.get("mail_pass", "") or os.environ.get("CHARON_MAIL_PASS", "")

    if not mail_server or not mail_from or not mail_to_list:
        raise DigestError(
            "Mail not configured. Set mail_server, mail_from, and mail_to in profile."
        )

    # Build digest after validation (so config errors surface even when empty)
    subject, body, entry_ids = build_digest()

    if not body:
        return False

    # Build email
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = mail_from
    msg["To"] = mail_to
    msg.attach(MIMEText(body, "plain", "utf-8"))

    try:
        with smtplib.SMTP(mail_server, mail_port, timeout=30) as server:
            server.ehlo()
            if server.has_extn("STARTTLS"):
                server.starttls()
                server.ehlo()
            if mail_user and mail_pass:
                server.login(mail_user, mail_pass)
            server.sendmail(mail_from, mail_to_list, msg.as_string())
    except smtplib.SMTPAuthenticationError:
        raise DigestError("SMTP authentication failed. Check mail_user and CHARON_MAIL_PASS.")
    except smtplib.SMTPException as e:
        raise DigestError(f"SMTP error: {type(e).__name__}. Check mail settings.")
    except OSError as e:
        raise DigestError(f"Connection failed: {e}. Check mail_server and mail_port.")

    # Mark entries as sent
    mark_digest_sent(entry_ids)
    return True


def preview_digest() -> str:
    """Generate digest preview without sending. Returns the body text."""
    _, body, _ = build_digest()
    return body
